### ISSUE TITLE
Raw depth images for the synthetic data

### ISSUE THREAD

**Issue by zhanggd18** [Shreeyak/cleargrasp#8]
Hi. Thank you for introducing your excellent work and database.
I find that there is only rectified depth images for the synthetic data (in depth-imgs-rectified ). For the real data, there are both transparent-depth-im (raw) and opaque-depth-img (rectified). Can you provide the raw depth images for the synthetic data?

**Comment by Shreeyak** [comment]
Thanks!
You might have misunderstood. In real images, transparent object's depth isn't detected, so we replace them with opaque objects to get their ground truth depth. Therefore we have a "transparent depth" (raw depth) and  "opaque depth" (ground truth depth):
![Copy of cleargrasp_blog_real_samples_old](https://user-images.githubusercontent.com/12800185/83359244-aeb8f400-a396-11ea-859f-a8003c06a0c1.jpg)


Synthetic data generates pixel-perfect ground truth using ray-tracing principles. Therefore, we directly get the ground truth depth images. We cannot generate "raw" depth in synthetic data, as modelling the noise caused by transparency in real stereo cameras is very difficult.
The original depth from rendering contains depth from camera center. The `depth-imgs-rectified` dir contains images where depth is converted so that depth is from camera plane, similar to stereo camera output:
![depth_recitification_example](https://user-images.githubusercontent.com/12800185/83359168-17ec3780-a396-11ea-9b6b-b664a06f639b.jpg)

**Comment by zhanggd18** [comment]
Thanks for your detailed explanation.

**Comment by kontramind** [comment]
Hi Shreeyak,

So, just to clarify, in the training data the rectified depth (from camera plane) is used and not the original one (from camera center)?

Many thanks
